apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-chart.fullname" . }}
  labels:
    {{- include "java-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.port }}
      targetPort: 8080
      port: 8080
      protocol: TCP
      name: http8080
  selector:
    {{- include "java-chart.selectorLabels" . | nindent 4 }}
    app: java-app
